
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Image image4;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.Notebook notebook1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.NodeView nodeview1;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.Button actualizarLista;
	private global::Gtk.Label label1;
	private global::Gtk.VPaned vpaned3;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.Label label6;
	private global::Gtk.Entry codigoGtxt;
	private global::Gtk.Entry telGtxt;
	private global::Gtk.Entry emailGtxt;
	private global::Gtk.Label label8;
	private global::Gtk.Label label9;
	private global::Gtk.Label label7;
	private global::Gtk.Entry nomGtxt;
	private global::Gtk.Button guardar;
	private global::Gtk.Label GtkLabel2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.NodeView nodeview2;
	private global::Gtk.Label label2;
	private global::Gtk.VPaned vpaned4;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Label label11;
	private global::Gtk.Entry idtxt;
	private global::Gtk.Button cargar;
	private global::Gtk.Button actualizar;
	private global::Gtk.Label label12;
	private global::Gtk.Label label13;
	private global::Gtk.Entry codigotxt;
	private global::Gtk.Entry nombretxt;
	private global::Gtk.Label label14;
	private global::Gtk.Label label15;
	private global::Gtk.Entry telefonotxt;
	private global::Gtk.Entry emailtxt;
	private global::Gtk.Label GtkLabel5;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.NodeView nodeview3;
	private global::Gtk.Label label3;
	private global::Gtk.VPaned vpaned5;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.Fixed fixed7;
	private global::Gtk.Label label16;
	private global::Gtk.Entry id2txt;
	private global::Gtk.Button cargar2;
	private global::Gtk.Button eliminar;
	private global::Gtk.Label GtkLabel9;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.NodeView nodeview4;
	private global::Gtk.Label label4;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Registro");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image ();
		this.image4.Name = "image4";
		this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Practica8.DirPer2.png");
		this.hbox2.Add (this.image4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.image4]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox2.Add (this.fixed2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fixed2]));
		w2.Position = 1;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView ();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add (this.nodeview1);
		this.vbox4.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow]));
		w5.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.HeightRequest = 37;
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		// Container child fixed4.Gtk.Fixed+FixedChild
		this.actualizarLista = new global::Gtk.Button ();
		this.actualizarLista.CanFocus = true;
		this.actualizarLista.Name = "actualizarLista";
		this.actualizarLista.UseUnderline = true;
		this.actualizarLista.Label = global::Mono.Unix.Catalog.GetString ("Actualizar Lista");
		this.fixed4.Add (this.actualizarLista);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.actualizarLista]));
		w6.X = 3;
		w6.Y = 3;
		this.vbox4.Add (this.fixed4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed4]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.notebook1.Add (this.vbox4);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Mostrar todo");
		this.notebook1.SetTabLabel (this.vbox4, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vpaned3 = new global::Gtk.VPaned ();
		this.vpaned3.CanFocus = true;
		this.vpaned3.Name = "vpaned3";
		this.vpaned3.Position = 165;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
		this.fixed5.Add (this.label6);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label6]));
		w9.X = 19;
		w9.Y = 13;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.codigoGtxt = new global::Gtk.Entry ();
		this.codigoGtxt.CanFocus = true;
		this.codigoGtxt.Name = "codigoGtxt";
		this.codigoGtxt.IsEditable = true;
		this.codigoGtxt.InvisibleChar = '•';
		this.fixed5.Add (this.codigoGtxt);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.codigoGtxt]));
		w10.X = 17;
		w10.Y = 35;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.telGtxt = new global::Gtk.Entry ();
		this.telGtxt.CanFocus = true;
		this.telGtxt.Name = "telGtxt";
		this.telGtxt.IsEditable = true;
		this.telGtxt.InvisibleChar = '•';
		this.fixed5.Add (this.telGtxt);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.telGtxt]));
		w11.X = 18;
		w11.Y = 96;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.emailGtxt = new global::Gtk.Entry ();
		this.emailGtxt.CanFocus = true;
		this.emailGtxt.Name = "emailGtxt";
		this.emailGtxt.IsEditable = true;
		this.emailGtxt.InvisibleChar = '•';
		this.fixed5.Add (this.emailGtxt);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.emailGtxt]));
		w12.X = 193;
		w12.Y = 96;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Telefono:");
		this.fixed5.Add (this.label8);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label8]));
		w13.X = 19;
		w13.Y = 72;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Correo Electronico:");
		this.fixed5.Add (this.label9);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label9]));
		w14.X = 193;
		w14.Y = 71;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
		this.fixed5.Add (this.label7);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.label7]));
		w15.X = 193;
		w15.Y = 14;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.nomGtxt = new global::Gtk.Entry ();
		this.nomGtxt.CanFocus = true;
		this.nomGtxt.Name = "nomGtxt";
		this.nomGtxt.IsEditable = true;
		this.nomGtxt.InvisibleChar = '•';
		this.fixed5.Add (this.nomGtxt);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.nomGtxt]));
		w16.X = 191;
		w16.Y = 35;
		// Container child fixed5.Gtk.Fixed+FixedChild
		this.guardar = new global::Gtk.Button ();
		this.guardar.CanFocus = true;
		this.guardar.Name = "guardar";
		this.guardar.UseUnderline = true;
		this.guardar.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
		this.fixed5.Add (this.guardar);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed5 [this.guardar]));
		w17.X = 380;
		w17.Y = 95;
		this.GtkAlignment.Add (this.fixed5);
		this.frame2.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Agregar Nuevo Registro</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel2;
		this.vpaned3.Add (this.frame2);
		global::Gtk.Paned.PanedChild w20 = ((global::Gtk.Paned.PanedChild)(this.vpaned3 [this.frame2]));
		w20.Resize = false;
		// Container child vpaned3.Gtk.Paned+PanedChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeview2 = new global::Gtk.NodeView ();
		this.nodeview2.CanFocus = true;
		this.nodeview2.Name = "nodeview2";
		this.GtkScrolledWindow1.Add (this.nodeview2);
		this.vpaned3.Add (this.GtkScrolledWindow1);
		this.notebook1.Add (this.vpaned3);
		global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vpaned3]));
		w23.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Agregar Nuevo");
		this.notebook1.SetTabLabel (this.vpaned3, this.label2);
		this.label2.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vpaned4 = new global::Gtk.VPaned ();
		this.vpaned4.CanFocus = true;
		this.vpaned4.Name = "vpaned4";
		this.vpaned4.Position = 167;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
		this.fixed6.Add (this.label11);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label11]));
		w24.X = 17;
		w24.Y = 14;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.idtxt = new global::Gtk.Entry ();
		this.idtxt.CanFocus = true;
		this.idtxt.Name = "idtxt";
		this.idtxt.IsEditable = true;
		this.idtxt.InvisibleChar = '•';
		this.fixed6.Add (this.idtxt);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.idtxt]));
		w25.X = 40;
		w25.Y = 9;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.cargar = new global::Gtk.Button ();
		this.cargar.CanFocus = true;
		this.cargar.Name = "cargar";
		this.cargar.UseUnderline = true;
		this.cargar.Label = global::Mono.Unix.Catalog.GetString ("Cargar");
		this.fixed6.Add (this.cargar);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.cargar]));
		w26.X = 215;
		w26.Y = 7;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.actualizar = new global::Gtk.Button ();
		this.actualizar.CanFocus = true;
		this.actualizar.Name = "actualizar";
		this.actualizar.UseUnderline = true;
		this.actualizar.Label = global::Mono.Unix.Catalog.GetString ("Actualizar");
		this.fixed6.Add (this.actualizar);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.actualizar]));
		w27.X = 279;
		w27.Y = 7;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Código:");
		this.fixed6.Add (this.label12);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label12]));
		w28.X = 15;
		w28.Y = 42;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
		this.fixed6.Add (this.label13);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label13]));
		w29.X = 183;
		w29.Y = 42;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.codigotxt = new global::Gtk.Entry ();
		this.codigotxt.CanFocus = true;
		this.codigotxt.Name = "codigotxt";
		this.codigotxt.IsEditable = true;
		this.codigotxt.InvisibleChar = '•';
		this.fixed6.Add (this.codigotxt);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.codigotxt]));
		w30.X = 12;
		w30.Y = 65;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.nombretxt = new global::Gtk.Entry ();
		this.nombretxt.CanFocus = true;
		this.nombretxt.Name = "nombretxt";
		this.nombretxt.IsEditable = true;
		this.nombretxt.InvisibleChar = '•';
		this.fixed6.Add (this.nombretxt);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.nombretxt]));
		w31.X = 185;
		w31.Y = 65;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Telefono:");
		this.fixed6.Add (this.label14);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label14]));
		w32.X = 14;
		w32.Y = 99;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Correo Electronico:");
		this.fixed6.Add (this.label15);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.label15]));
		w33.X = 183;
		w33.Y = 101;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.telefonotxt = new global::Gtk.Entry ();
		this.telefonotxt.CanFocus = true;
		this.telefonotxt.Name = "telefonotxt";
		this.telefonotxt.IsEditable = true;
		this.telefonotxt.InvisibleChar = '•';
		this.fixed6.Add (this.telefonotxt);
		global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.telefonotxt]));
		w34.X = 10;
		w34.Y = 120;
		// Container child fixed6.Gtk.Fixed+FixedChild
		this.emailtxt = new global::Gtk.Entry ();
		this.emailtxt.CanFocus = true;
		this.emailtxt.Name = "emailtxt";
		this.emailtxt.IsEditable = true;
		this.emailtxt.InvisibleChar = '•';
		this.fixed6.Add (this.emailtxt);
		global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed6 [this.emailtxt]));
		w35.X = 185;
		w35.Y = 120;
		this.GtkAlignment1.Add (this.fixed6);
		this.frame3.Add (this.GtkAlignment1);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Editar Registro</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel5;
		this.vpaned4.Add (this.frame3);
		global::Gtk.Paned.PanedChild w38 = ((global::Gtk.Paned.PanedChild)(this.vpaned4 [this.frame3]));
		w38.Resize = false;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeview3 = new global::Gtk.NodeView ();
		this.nodeview3.CanFocus = true;
		this.nodeview3.Name = "nodeview3";
		this.GtkScrolledWindow2.Add (this.nodeview3);
		this.vpaned4.Add (this.GtkScrolledWindow2);
		this.notebook1.Add (this.vpaned4);
		global::Gtk.Notebook.NotebookChild w41 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vpaned4]));
		w41.Position = 2;
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Editar");
		this.notebook1.SetTabLabel (this.vpaned4, this.label3);
		this.label3.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vpaned5 = new global::Gtk.VPaned ();
		this.vpaned5.CanFocus = true;
		this.vpaned5.Name = "vpaned5";
		this.vpaned5.Position = 99;
		// Container child vpaned5.Gtk.Paned+PanedChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("ID:");
		this.fixed7.Add (this.label16);
		global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.label16]));
		w42.X = 13;
		w42.Y = 28;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.id2txt = new global::Gtk.Entry ();
		this.id2txt.CanFocus = true;
		this.id2txt.Name = "id2txt";
		this.id2txt.IsEditable = true;
		this.id2txt.InvisibleChar = '•';
		this.fixed7.Add (this.id2txt);
		global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.id2txt]));
		w43.X = 34;
		w43.Y = 25;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.cargar2 = new global::Gtk.Button ();
		this.cargar2.CanFocus = true;
		this.cargar2.Name = "cargar2";
		this.cargar2.UseUnderline = true;
		this.cargar2.Label = global::Mono.Unix.Catalog.GetString ("Cargar");
		this.fixed7.Add (this.cargar2);
		global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.cargar2]));
		w44.X = 205;
		w44.Y = 24;
		// Container child fixed7.Gtk.Fixed+FixedChild
		this.eliminar = new global::Gtk.Button ();
		this.eliminar.CanFocus = true;
		this.eliminar.Name = "eliminar";
		this.eliminar.UseUnderline = true;
		this.eliminar.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
		this.fixed7.Add (this.eliminar);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed7 [this.eliminar]));
		w45.X = 271;
		w45.Y = 24;
		this.GtkAlignment2.Add (this.fixed7);
		this.frame4.Add (this.GtkAlignment2);
		this.GtkLabel9 = new global::Gtk.Label ();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Eeliminar Registro</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel9;
		this.vpaned5.Add (this.frame4);
		global::Gtk.Paned.PanedChild w48 = ((global::Gtk.Paned.PanedChild)(this.vpaned5 [this.frame4]));
		w48.Resize = false;
		// Container child vpaned5.Gtk.Paned+PanedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.nodeview4 = new global::Gtk.NodeView ();
		this.nodeview4.CanFocus = true;
		this.nodeview4.Name = "nodeview4";
		this.GtkScrolledWindow3.Add (this.nodeview4);
		this.vpaned5.Add (this.GtkScrolledWindow3);
		this.notebook1.Add (this.vpaned5);
		global::Gtk.Notebook.NotebookChild w51 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vpaned5]));
		w51.Position = 3;
		// Notebook tab
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Eliminar");
		this.notebook1.SetTabLabel (this.vpaned5, this.label4);
		this.label4.ShowAll ();
		this.vbox3.Add (this.notebook1);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook1]));
		w52.Position = 1;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 517;
		this.DefaultHeight = 350;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.actualizarLista.Clicked += new global::System.EventHandler (this.OnActualizarListaClicked);
		this.guardar.Clicked += new global::System.EventHandler (this.OnGuardarClicked);
		this.cargar.Clicked += new global::System.EventHandler (this.OnCargarClicked);
		this.actualizar.Clicked += new global::System.EventHandler (this.OnActualizarClicked);
		this.cargar2.Clicked += new global::System.EventHandler (this.OnCargar2Clicked);
		this.eliminar.Clicked += new global::System.EventHandler (this.OnEliminarClicked);
	}
}
